"""Hand-computed Cairo ladder expectations, not outputs generated by the ladder."""

from datetime import datetime
from zoneinfo import ZoneInfo

import pytest
from domain_fixtures import mission

from sanad.contact.ladder import computed_local, plan_next_contact
from sanad.contact.policy import DRAFT_CONTACT_POLICY as POLICY
from sanad.domain import DRAFT_POLICY_2026_09, Mission, PatientScope, VersionRef
from sanad.domain.entities import (
    MedicationDetails,
    SendRecordsDetails,
    TaskDetails,
    VisitDetails,
)
from sanad.domain.entities import (
    TestDetails as LabDetails,
)
from sanad.domain.predicates import PatientReportPredicate
from sanad.store.records import Consent, Patient, PatientProfile


def utc(s: str) -> datetime:
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


# kind, confirm UTC, explicit due UTC, quiet, pause UTC, expected accepted UTCs, expected locals.
type Row = tuple[str, str, str, tuple[str, str], str | None, list[str], list[str]]

TABLE: list[Row] = [
    (
        "TEST",
        "2026-09-07T06:00Z",
        "2026-09-21T07:00Z",
        ("22:00", "08:00"),
        None,
        ["2026-09-07T07:00Z", "2026-09-14T07:00Z", "2026-09-20T07:00Z"],
        ["09-07 10:00", "09-14 10:00", "09-20 10:00"],
    ),
    (
        "VISIT",
        "2026-09-07T06:00Z",
        "2026-10-07T07:00Z",
        ("22:00", "08:00"),
        None,
        ["2026-09-07T07:00Z", "2026-09-22T07:00Z", "2026-10-06T07:00Z"],
        ["09-07 10:00", "09-22 10:00", "10-06 10:00"],
    ),
    (
        "TASK",
        "2026-09-07T06:00Z",
        "2026-09-14T07:00Z",
        ("22:00", "08:00"),
        None,
        ["2026-09-07T07:00Z", "2026-09-10T07:00Z", "2026-09-13T07:00Z"],
        ["09-07 10:00", "09-10 10:00", "09-13 10:00"],
    ),
    (
        "SEND_RECORDS",
        "2026-09-07T06:00Z",
        "2026-09-10T07:00Z",
        ("22:00", "08:00"),
        None,
        ["2026-09-07T07:00Z", "2026-09-08T07:00Z", "2026-09-09T07:00Z"],
        ["09-07 10:00", "09-08 10:00", "09-09 10:00"],
    ),
    (
        "MEDICATION",
        "2026-09-07T06:00Z",
        "2026-09-10T07:00Z",
        ("22:00", "08:00"),
        None,
        ["2026-09-07T07:00Z", "2026-09-08T07:00Z", "2026-09-09T07:00Z"],
        ["09-07 10:00", "09-08 10:00", "09-09 10:00"],
    ),
    (
        "TEST",
        "2026-09-07T06:00Z",
        "2026-09-09T07:00Z",
        ("22:00", "08:00"),
        None,
        ["2026-09-07T07:00Z", "2026-09-08T07:00Z"],
        ["09-07 10:00", "09-08 10:00"],
    ),
    (
        "TEST",
        "2026-09-07T06:00Z",
        "2026-09-21T07:00Z",
        ("09:00", "12:00"),
        None,
        ["2026-09-07T09:00Z", "2026-09-14T09:00Z", "2026-09-20T09:00Z"],
        ["09-07 12:00", "09-14 12:00", "09-20 12:00"],
    ),
    (
        "TEST",
        "2026-09-07T06:00Z",
        "2026-09-21T07:00Z",
        ("22:00", "08:00"),
        "2026-09-10T09:00Z",
        ["2026-09-10T09:00Z", "2026-09-15T07:00Z", "2026-09-20T07:00Z"],
        ["09-10 12:00", "09-15 10:00", "09-20 10:00"],
    ),
    (
        "TEST",
        "2026-10-20T06:00Z",
        "2026-11-03T06:00Z",
        ("22:00", "08:00"),
        None,
        ["2026-10-20T07:00Z", "2026-10-27T07:00Z", "2026-11-02T08:00Z"],
        ["10-20 10:00", "10-27 10:00", "11-02 10:00"],
    ),
    (
        "TEST",
        "2026-04-20T06:00Z",
        "2026-05-04T06:00Z",
        ("22:00", "08:00"),
        None,
        ["2026-04-20T08:00Z", "2026-04-27T07:00Z", "2026-05-03T07:00Z"],
        ["04-20 10:00", "04-27 10:00", "05-03 10:00"],
    ),
    (
        "TASK",
        "2026-04-23T06:00Z",
        "2026-04-28T07:00Z",
        ("09:00", "12:00"),
        None,
        ["2026-04-23T10:00Z", "2026-04-25T09:00Z", "2026-04-27T09:00Z"],
        ["04-23 12:00", "04-25 12:00", "04-27 12:00"],
    ),
    (
        "VISIT",
        "2026-10-28T06:00Z",
        "2026-11-05T08:00Z",
        ("09:00", "12:00"),
        None,
        ["2026-10-28T09:00Z", "2026-11-01T10:00Z", "2026-11-04T10:00Z"],
        ["10-28 12:00", "11-01 12:00", "11-04 12:00"],
    ),
]


def setup(row: Row) -> tuple[Mission, Patient, Consent, PatientProfile]:
    kind, confirmed, due, quiet, pause, _, _ = row
    start = utc(confirmed)
    scope = PatientScope(doctor_id="synthetic-doctor", patient_id="synthetic-patient")
    patient = Patient(
        id=scope.patient_id,
        scope=scope,
        display_name="Synthetic",
        language="ar",
        timezone="Africa/Cairo",
        contact_status="active",
        active_binding_id="bound",
        consent_id="consent",
        consent_version=1,
        created_at=start,
        updated_at=start,
    )
    consent = Consent(
        id="consent",
        scope=scope,
        binding_id="bound",
        policy_text_version="synthetic",
        accepted_at=start,
        accepted_by="123",
        quiet_hours=quiet,
        timezone="Africa/Cairo",
        urgent_response_policy_id="synthetic",
        policy_digest="synthetic",
        created_at=start,
        updated_at=start,
    )
    profile = PatientProfile(
        id=scope.patient_id,
        patient_id=scope.patient_id,
        doctor_id=scope.doctor_id,
        binding_active=True,
        consent_active=True,
        recipient_ref="123",
        created_at=start,
        updated_at=start,
        routine_paused_until=utc(pause) if pause else None,
    )
    details = {
        "TEST": LabDetails(analytes=("K",), completeness="all"),
        "VISIT": VisitDetails(objective="attendance_reported"),
        "TASK": TaskDetails(category="report", instruction="report", completion_rule="report"),
        "SEND_RECORDS": SendRecordsDetails(categories=("labs",), required_count=1),
        "MEDICATION": MedicationDetails(
            action="START", order_ref=VersionRef(entity_type="care_order", id="drug", version=1)
        ),
    }[kind]
    m = mission(
        kind=kind,
        details=details,
        objective_predicate=PatientReportPredicate(report_kind="start")
        if kind == "MEDICATION"
        else mission().objective_predicate,
        confirmed_at=start,
        created_at=start,
        updated_at=start,
        due_at=utc(due),
        escalation_at=utc(due),
    )
    return m, patient, consent, profile


@pytest.mark.parametrize("row", TABLE, ids=[f"handwritten-{i}" for i in range(1, 13)])
def test_handwritten_ladder(row: Row) -> None:
    m, patient, consent, profile = setup(row)
    original = (m.due_at, m.escalation_at, m.original_time_expression, m.timing_anchor)
    for count, (instant, local) in enumerate(zip(row[5], row[6], strict=True)):
        plan = plan_next_contact(
            m, patient, consent, profile, POLICY, DRAFT_POLICY_2026_09, m.updated_at
        )
        assert plan and plan.at == utc(instant)
        assert plan.at.astimezone(ZoneInfo(patient.timezone)).strftime("%m-%d %H:%M") == local
        assert (
            plan.slot_id
            == "chase:" + plan.at.astimezone(ZoneInfo(patient.timezone)).date().isoformat()
        )
        m = m.model_copy(
            update={
                "contact_count": count + 1,
                "first_chase_accepted_at": m.first_chase_accepted_at or plan.at,
                "last_chase_accepted_at": plan.at,
            }
        )
        profile = profile.model_copy(
            update={"last_chase_accepted_at": plan.at, "routine_paused_until": None}
        )
    assert (
        plan_next_contact(m, patient, consent, profile, POLICY, DRAFT_POLICY_2026_09, m.updated_at)
        is None
    )
    assert (m.due_at, m.escalation_at, m.original_time_expression, m.timing_anchor) == original


@pytest.mark.parametrize(
    "local,expected",
    [("2026-04-24T00:30", "2026-04-23T22:30Z"), ("2026-10-29T23:30", "2026-10-29T21:30Z")],
)
def test_computed_dst_fold_and_gap_choose_later(local: str, expected: str) -> None:
    assert computed_local(datetime.fromisoformat(local), "Africa/Cairo") == utc(expected)


@pytest.mark.parametrize("action", ["STOP", "CHANGE"])
def test_doctor_acknowledgment_medication_missions_are_not_chased(action: str) -> None:
    from sanad.contact.ladder import reason_for

    m, patient, consent, profile = setup(TABLE[4])
    m = m.model_copy(update={"details": m.details.model_copy(update={"action": action})})
    assert reason_for(m, patient, consent, profile, POLICY) == "blocked"
    assert (
        plan_next_contact(m, patient, consent, profile, POLICY, DRAFT_POLICY_2026_09, m.updated_at)
        is None
    )


def test_after_escalation_reason_is_observable_without_a_plan() -> None:
    from sanad.contact.ladder import reason_for

    m, patient, consent, profile = setup(TABLE[0])
    profile = profile.model_copy(update={"routine_paused_until": m.escalation_at})
    assert reason_for(m, patient, consent, profile, POLICY) == "after_escalation"
    assert (
        plan_next_contact(m, patient, consent, profile, POLICY, DRAFT_POLICY_2026_09, m.updated_at)
        is None
    )
